import axios from 'axios';
import { config } from '../config.js';

export async function createHubSpotActions(deal, signals, analysis) {
  try {
    // Create task
    await createTask(deal, signals, analysis);

    // Add note
    await addNote(deal, signals, analysis);

    // Update deal properties (optional, may fail if custom properties don't exist)
    try {
      await updateDealProperties(deal, signals, analysis);
    } catch (propError) {
      console.warn(`  ⚠️  Could not update custom properties: ${propError.message}`);
    }

  } catch (error) {
    console.error('\n🔍 DEBUG - HubSpot Actions Error:');
    console.error('Status:', error.response?.status);
    console.error('Status Text:', error.response?.statusText);
    console.error('Data:', JSON.stringify(error.response?.data, null, 2));
    throw new Error(`Failed to create HubSpot actions: ${error.message}`);
  }
}

async function createTask(deal, signals, analysis) {
  const signalList = signals.map(s => `• ${s.description}`).join('\n');
  const talkingPoints = analysis.talking_points.map(p => `• ${p}`).join('\n');

  const taskBody = `## Revival Opportunity Detected

**Company:** ${deal.companyName}
**Original Deal:** $${deal.amount}
**Lost:** ${getMonthsSince(deal.closeDate)} months ago
**Lost Reason:** ${deal.lostReason}

---

## Signals Detected

${signalList}

---

## AI Analysis

**Confidence Score:** ${analysis.confidence_score}/10

${analysis.summary}

---

## Suggested Email

${analysis.email_draft}

---

## Talking Points

${talkingPoints}

---

*Generated by ReviveIQ • ${new Date().toLocaleString()}*`;

  const dueDate = new Date();
  dueDate.setDate(dueDate.getDate() + 3); // Due in 3 days

  const taskProperties = {
    hs_task_subject: `🔥 ReviveIQ: ${deal.companyName} showing revival signals`,
    hs_task_body: taskBody,
    hs_task_status: 'NOT_STARTED',
    hs_task_priority: 'HIGH',
    hs_timestamp: dueDate.getTime().toString()
  };

  // Only add owner if it exists
  if (deal.ownerId) {
    taskProperties.hubspot_owner_id = deal.ownerId;
  }

  const taskPayload = {
    properties: taskProperties
  };

  const response = await axios.post(
    `${config.hubspot.baseUrl}/crm/v3/objects/tasks`,
    taskPayload,
    {
      headers: {
        'Authorization': `Bearer ${config.hubspot.accessToken}`,
        'Content-Type': 'application/json'
      }
    }
  );

  // Associate task with deal using v4 API
  try {
    await axios.put(
      `${config.hubspot.baseUrl}/crm/v4/objects/tasks/${response.data.id}/associations/deals/${deal.id}`,
      [
        {
          associationCategory: "HUBSPOT_DEFINED",
          associationTypeId: 216
        }
      ],
      {
        headers: {
          'Authorization': `Bearer ${config.hubspot.accessToken}`,
          'Content-Type': 'application/json'
        }
      }
    );
  } catch (associationError) {
    console.warn(`  ⚠️  Could not associate task with deal: ${associationError.message}`);
  }
}

async function addNote(deal, signals, analysis) {
  const signalList = signals.map(s => `• ${s.type}: ${s.description}`).join('\n');

  const noteBody = `ReviveIQ detected ${signals.length} revival signal(s):

${signalList}

AI Confidence: ${analysis.confidence_score}/10

${analysis.summary}`;

  const notePayload = {
    properties: {
      hs_note_body: noteBody,
      hs_timestamp: Date.now().toString()
    }
  };

  const response = await axios.post(
    `${config.hubspot.baseUrl}/crm/v3/objects/notes`,
    notePayload,
    {
      headers: {
        'Authorization': `Bearer ${config.hubspot.accessToken}`,
        'Content-Type': 'application/json'
      }
    }
  );

  // Associate note with deal using v4 API
  try {
    await axios.put(
      `${config.hubspot.baseUrl}/crm/v4/objects/notes/${response.data.id}/associations/deals/${deal.id}`,
      [
        {
          associationCategory: "HUBSPOT_DEFINED",
          associationTypeId: 214
        }
      ],
      {
        headers: {
          'Authorization': `Bearer ${config.hubspot.accessToken}`,
          'Content-Type': 'application/json'
        }
      }
    );
  } catch (associationError) {
    console.warn(`  ⚠️  Could not associate note with deal: ${associationError.message}`);
  }
}

async function updateDealProperties(deal, signals, analysis) {
  const signalTypes = signals.map(s => s.type).join(';');

  const updatePayload = {
    properties: {
      reviveiq_signal_detected: true,
      reviveiq_signal_type: signalTypes,
      reviveiq_last_scan: new Date().getTime(),
      reviveiq_confidence: analysis.confidence_score
    }
  };

  await axios.patch(
    `${config.hubspot.baseUrl}/crm/v3/objects/deals/${deal.id}`,
    updatePayload,
    {
      headers: {
        'Authorization': `Bearer ${config.hubspot.accessToken}`,
        'Content-Type': 'application/json'
      }
    }
  );
}

function getMonthsSince(date) {
  return Math.round((Date.now() - date.getTime()) / (1000 * 60 * 60 * 24 * 30));
}
